platform :ios, '8.0'

use_frameworks!

# ignore all warnings from all pods(注解)
inhibit_all_warnings!

target 'JXSourceFile' do
    
    # 网络请求
    pod 'AFNetworking'
    
    # 自动布局
    pod 'Masonry'
    
    # 图片加载
    pod 'SDWebImage'
    
    # 网络状态监听
    pod 'Reachability'
    
    # 刷新控件
    pod 'MJRefresh'
    
    #使用静态直播库
    pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_live'
    
end

#Xcode里配置：项目名->Target->Build Settings->Enable BitCode中设置为NO就可以了.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
